#!/usr/bin/env python3

import rospy
import numpy as np
import os
import atexit

from datetime import datetime

from nav_msgs.msg import OccupancyGrid

class mapCompare:
    def __init__(self, mode):
        atexit.register(self.exit_handler)
        self.map = None
        self.mode = mode
        self.date_string = datetime.now().strftime("%Y-%m-%d-%H:%M:%S")
        self.differenceArray = []
        self.stopTime = int(rospy.get_param('~stop_time', '500'))

    def exit_handler(self):
        date_string = self.date_string

        file_name = date_string + '.txt'
        file_location = 'catkin_ws/src/TU_Much_Exploration/tme_data/coverage'
        file_location = os.path.join(os.path.expanduser('~'), file_location)
        file_complete = os.path.join(os.path.expanduser('~'), file_location, file_name)

        if(not self.mode):
            a_file = open(file_complete, 'w+')
            np.savetxt(a_file, self.map)
            a_file.close()
            rospy.logwarn('created file named: ' + file_complete)
        else:
            a_file = open(file_complete, 'w+')
            np.savetxt(a_file, self.differenceArray)
            a_file.close()
            rospy.logwarn('created file named: ' + file_complete)

        
        #add image to verify validity

    def get_map(self):
        return self.map

    def get_mode(self):
        return self.mode

    def get_date_string(self):
        return self.date_string

    def get_differenceArrray(self):
        return self.differenceArray
    
    def get_stopTime(self):
        return self.stopTime

    def set_differenceArray(self, data):
        self.differenceArray = data

    def compare_images(self):
        pass

    def callback_map(self, data):
        self.map = data.data

if __name__ == '__main__':

    rospy.init_node('map_compare')
    
    rate = rospy.Rate(0.2)

    #0 is log array, 1 is compare and log
    classy = mapCompare(mode=1)
    mode = classy.mode

    file_name = classy.get_date_string()
    file_location = 'catkin_ws/src/TU_Much_Exploration/tme_data/coverage/measurements'
    file_location = os.path.join(os.path.expanduser('~'), file_location)
    file_complete = os.path.join(os.path.expanduser('~'), file_location, file_name)

    map_file_name = 'maze_map.txt'
    map_file_location = 'catkin_ws/src/TU_Much_Exploration/tme_data/coverage/base_line'
    base_file = os.path.join(os.path.expanduser('~'), map_file_location, map_file_name)
    baseLine = np.loadtxt(base_file)

    rospy.Subscriber('/map', OccupancyGrid, callback=classy.callback_map)

    time_estimate = 0

    base_difference = np.full((1042, 1040), -1)
    base_metric = np.mean(baseLine != base_difference)

    stopTime = classy.get_stopTime()

    while not rospy.is_shutdown():

        if(mode):
            os.system('rosrun map_server map_saver -f ' + str(file_complete))

            localMap = classy.get_map()
            difference = np.mean(baseLine != localMap)

            localArray = classy.get_differenceArrray()
            temp_time = time_estimate
            test = [temp_time, difference]
            time_estimate += 5
            localArray.append(test)

        if(time_estimate >= stopTime):
            os.system('rosnode kill -a')

        rate.sleep()