#!/usr/bin/env python3

import string
import numpy as np
import os
import roslaunch

def runner(numRobots = 2, world = 'v2_maze', method = 'combined', stopTime = 400, tries = 10):
    os.environ["tme_start_num"] = str(numRobots)
    os.environ["tme_stop_time"] = str(stopTime)
    print(method)
    os.environ["tme_expl_method"] = str(method)
    os.environ["tme_ROBOT_ENV"] = str(world)
    os.environ["tme_ROBOT"] = 'rto-1'

    start_two = False
    start_three = False
    start_four = False
    start_five = False

    if (numRobots >= 2):
        start_two = True
        if (numRobots >= 3):
            start_three = True
            if (numRobots >= 4):
                start_four = True
                if (numRobots >= 5):
                    start_five = True

    os.environ["tme_start_two"] = str(start_two)
    os.environ["tme_start_three"] = str(start_three)
    os.environ["tme_start_four"] = str(start_four)
    os.environ["tme_start_five"] = str(start_five)

    file_location = 'catkin_ws/src/TU_Much_Exploration/tme_startup/launch'
    file_name = "decentralized_launch.launch"
    file_name = os.path.join(os.path.expanduser('~'), file_location, file_name)
    
    for i in range(tries):
        os.system('roslaunch tme_startup decentralized_launch.launch')

def runAll(numRobots = 2, world = 'v2_maze', methods = ['coExplore'], stopTime=400, tries = 10):
    for i in range(len(methods)):
        runner(numRobots, world, methods[i], stopTime, tries)

if __name__ == '__main__':

    numRobots = [2, 3, 4, 5]
    world = ['marty', 'map_3'] #'v2_maze', 'map_3', 'marty'
    method = ['nearest', 'minPos'] #[['nearest'], ['greedy'], ['minPos'], ['combined'], ['coExplore']]
    stopTime = [500, 400, 300, 250]
    tries = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
    for x in range(len(tries)):
        for j in range(len(numRobots)):
            for i in range(len(world)):
                for y in range(len(method)):
                    runner(numRobots[j], world[i], method[y], stopTime[j], tries[x])
