#!/usr/bin/env python3
import roslib
import rospy
import math
import tf
import geometry_msgs.msg
from geometry_msgs.msg import Point, Quaternion, Pose
from gazebo_msgs.srv import GetModelState

"""
    This node listens to the postion of the blind robot in gazebo 
    simlulation for testing purposes.
"""

if __name__ == '__main__':

    rospy.init_node('gazebo_pos_listener')

    name = rospy.get_param('~name')
    pub = rospy.Publisher('pose', Pose, queue_size=10)

    rate = rospy.Rate(10.0)
    while not rospy.is_shutdown():
        
        try:
            gms = rospy.ServiceProxy('/gazebo/get_model_state', GetModelState)
            model = gms(name,"")
            pub.publish(model.pose)

        except rospy.ServiceException as e:
            rospy.loginfo("Get Model State service call failed:  {0}".format(e))

        rate.sleep()