#!/usr/bin/env python3
import roslib
import rospy
import math
import tf
import geometry_msgs.msg
from geometry_msgs.msg import Point, Quaternion, Pose

"""
    Position listener

        This node listens to the transforms between the merged map and robots baselink and
        it publishes the position of the robot in the merged map frame
"""

if __name__ == '__main__':
    rospy.init_node('turtle_tf_listener')
    position = Point()
    orientation = Quaternion()
    pose = Pose()
    listener = tf.TransformListener()
    name = rospy.get_param('~name')
    pub = rospy.Publisher('pose', Pose, queue_size=10)

    rate = rospy.Rate(10.0)
    while not rospy.is_shutdown():
        try:
            #listen to the transform between map and baselink
            (trans,rot) = listener.lookupTransform('map', f'{name}/base_link', rospy.Time(0))
        except (tf.LookupException, tf.ConnectivityException, tf.ExtrapolationException):
            continue

        position.x = trans[0]
        position.y = trans[1]
        position.z = trans[2]
        orientation.x = rot[0]
        orientation.y = rot[1]
        orientation.z = rot[2]
        orientation.w = rot[3]
        pose.position = position
        pose.orientation = orientation
        #publish the robot pose
        pub.publish(pose)
        rate.sleep()